onlyBuiltDependencies:
  - '@ibm/plex-sans-tc'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - dprint
  - sharp
  - unrs-resolver

patchedDependencies:
  graphql-tag: patches/graphql-tag.patch
