export const ERROR_NOT_FOUND = "NOT_FOUND";
export const ERROR_UNAUTHORIZED = "UNAUTHORIZED";
export const ERROR_USER_VERIFIED = "USER_VERIFIED";
export const ERROR_NOT_IMPLEMENTED = "NOT_IMPLEMENTED";
export const ERROR_FORBIDDEN = "FORBIDDEN";
